# Generated by Django 6.0.2 on 2026-03-23 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Category code (e.g., MAKANAN, MINUMAN, ELEKTRONIK)', max_length=20)),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional category description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business owner of this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='idx_category_business_active'), models.Index(fields=['business', 'code'], name='idx_category_business_code')],
                'unique_together': {('business', 'code')},
            },
        ),
    ]
