# Generated by Django 6.0.2 on 2026-04-05 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Supplier code (e.g., SUP001, SUP002)', max_length=20)),
                ('name', models.CharField(help_text='Supplier company name', max_length=100)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Supplier address')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supplier is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business owner of this supplier', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Product code (SKU, barcode, etc.)', max_length=30)),
                ('name', models.CharField(help_text='Product name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional product description')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price from supplier', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Retail selling price', max_digits=12)),
                ('unit', models.CharField(default='PCS', help_text='Unit type (PCS, BOX, KG, etc.)', max_length=20)),
                ('min_stock', models.IntegerField(default=0, help_text='Minimum stock level for reorder alert')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business owner of this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business')),
                ('category', models.ForeignKey(help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('supplier', models.ForeignKey(blank=True, help_text='Primary supplier for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'is_active'], name='idx_supplier_business_active'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'code'], name='idx_supplier_business_code'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('business', 'code')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='idx_product_business_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'code'], name='idx_product_business_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'category'], name='idx_product_business_category'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'code')},
        ),
    ]
