# Generated by Django 6.0.2 on 2026-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_supplier_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode / EAN / UPC for scanner input', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Product code (SKU)', max_length=30),
        ),
    ]
