# Generated by Django 6.0.2 on 2026-06-11 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
        ('products', '0003_product_barcode_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Discount name (e.g., Promo Lebaran)', max_length=100)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (Rp)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or amount)', max_digits=12)),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum quantity required to get this discount (0 means no minimum)')),
                ('is_all_products', models.BooleanField(default=True, help_text='If True, applies to all products. If False, specific products must be selected.')),
                ('start_date', models.DateTimeField(blank=True, help_text='When the discount starts', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the discount ends', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this discount rule is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business owner of this discount rule', on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='businesses.business')),
                ('products', models.ManyToManyField(blank=True, help_text='Specific products this rule applies to', related_name='discount_rules', to='products.product')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'db_table': 'discount_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
