# Generated by Django 6.0.2 on 2026-06-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_discountrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountRule',
        ),
    ]
