# Generated by Django 6.0.2 on 2026-06-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
        ('products', '0003_product_barcode_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('LOW_STOCK', 'Stok Rendah'), ('OUT_OF_STOCK', 'Stok Habis')], default='LOW_STOCK', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='products.product')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='accounts.businessuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
