# Generated by Django 6.0.2 on 2026-04-05 16:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment'), ('RETURN', 'Return')], help_text='Type of movement', max_length=10)),
                ('quantity', models.IntegerField(help_text='Quantity changed')),
                ('notes', models.TextField(blank=True, help_text='Reason or notes for movement')),
                ('reference_id', models.CharField(blank=True, help_text='Reference to transaction (e.g., transaction ID)', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(help_text='Business', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='Batch code (lot number, serial, etc.)', max_length=50)),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity in stock')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, help_text='Date batch was received')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (null if no expiry)', null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of this batch', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted')], default='ACTIVE', help_text='Batch status', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business owner of this batch', on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'db_table': 'product_batch',
                'ordering': ['purchase_date'],
            },
        ),
    ]
