# Generated by Django 6.0.2 on 2026-04-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_supplier_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(help_text='Product this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='batch',
            field=models.ForeignKey(help_text='Product batch affected', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.productbatch'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['business', 'product'], name='idx_batch_business_product'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['business', 'status'], name='idx_batch_business_status'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['expiry_date'], name='idx_batch_expiry_date'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('business', 'product', 'batch_code')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['business', 'batch'], name='idx_movement_business_batch'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='idx_movement_created_at'),
        ),
    ]
