# Generated by Django 6.0.2 on 2026-05-21 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current quantity in stock', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
