# Generated by Django 6.0.2 on 2026-06-12 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
        ('inventory', '0003_alter_productbatch_quantity'),
        ('products', '0005_delete_discountrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('created_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_opnames', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Stock Opname',
                'verbose_name_plural': 'Stock Opnames',
                'db_table': 'stock_opname',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOpnameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField(help_text='Stock in system at time of opname')),
                ('actual_qty', models.IntegerField(help_text='Actual physical stock counted')),
                ('difference', models.IntegerField(help_text='actual_qty - system_qty')),
                ('opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockopname')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'stock_opname_item',
            },
        ),
    ]
