# Generated by Django 6.0.2 on 2026-06-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
        ('products', '0005_delete_discountrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Promo Beli 2 Galon Diskon 7%', max_length=200)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Persentase (%)'), ('NOMINAL', 'Nominal (Rp)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Isi persentase (contoh: 10 untuk 10%) atau nominal (contoh: 5000 untuk Rp 5.000)', max_digits=12)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimal pembelian item (pada produk yang dipilih) agar diskon berlaku. Contoh: 2 untuk beli 2 dapat diskon.')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='businesses.business')),
                ('products', models.ManyToManyField(blank=True, help_text='Produk yang terkena diskon ini. Jika kosong, diskon TIDAK berlaku kemana-mana.', related_name='discounts', to='products.product')),
            ],
            options={
                'db_table': 'promotions_discount_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
