# Generated by Django 6.0.2 on 2026-05-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('CASH', 'Tunai'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer Bank'), ('EWALLET', 'E-Wallet'), ('CARD', 'Kartu Debit/Kredit')], max_length=20)),
                ('name', models.CharField(help_text="Nama tampilan, e.g. 'BCA', 'GoPay', 'QRIS Toko'", max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Nomor rekening/akun', max_length=100)),
                ('account_name', models.CharField(blank=True, help_text='Nama pemilik rekening', max_length=100)),
                ('qris_image', models.ImageField(blank=True, help_text='Gambar QR Code QRIS', null=True, upload_to='qris/')),
                ('instructions', models.TextField(blank=True, help_text='Instruksi pembayaran tambahan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='businesses.business')),
            ],
            options={
                'ordering': ['method_type', 'name'],
                'unique_together': {('business', 'method_type', 'name')},
            },
        ),
    ]
