# Generated by Django 6.0.2 on 2026-06-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XenditInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('xendit_invoice_id', models.CharField(blank=True, max_length=200)),
                ('invoice_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Sudah Dibayar'), ('EXPIRED', 'Kadaluwarsa'), ('FAILED', 'Gagal')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('payment_channel', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xendit_invoices', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
