# Generated by Django 6.0.2 on 2026-06-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
        ('payments', '0002_xendit_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='use_xendit',
            field=models.BooleanField(default=False, help_text='Gunakan Xendit untuk proses pembayaran otomatis'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='xendit_channel',
            field=models.CharField(blank=True, help_text='Channel Xendit: BCA, BNI, ID_GOPAY, dll', max_length=50),
        ),
        migrations.CreateModel(
            name='XenditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200, unique=True)),
                ('xendit_id', models.CharField(blank=True, max_length=200)),
                ('payment_type', models.CharField(choices=[('QRIS', 'QRIS'), ('VA', 'Virtual Account'), ('EWALLET', 'E-Wallet')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Sudah Dibayar'), ('EXPIRED', 'Kadaluwarsa'), ('FAILED', 'Gagal')], default='PENDING', max_length=20)),
                ('qr_string', models.TextField(blank=True, help_text='QR string untuk dirender jadi QR code (QRIS)')),
                ('va_number', models.CharField(blank=True, help_text='Nomor Virtual Account', max_length=50)),
                ('bank_code', models.CharField(blank=True, help_text='Kode bank: BCA, BNI, BRI, dll', max_length=20)),
                ('channel_code', models.CharField(blank=True, help_text='Channel eWallet: ID_GOPAY, ID_OVO, dll', max_length=50)),
                ('payment_url', models.URLField(blank=True, help_text='URL redirect pembayaran (eWallet)')),
                ('payment_channel', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xendit_payments', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='XenditInvoice',
        ),
    ]
