# Generated by Django 6.0.2 on 2026-03-15 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Technical Administrator',
                'verbose_name_plural': 'Technical Administrators',
                'db_table': 'technical_admin',
            },
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Business Admin/Owner'), ('kasir', 'Kasir/Cashier')], default='admin', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('schedule', models.CharField(blank=True, help_text="Kasir work schedule: e.g., 'senin,selasa,rabu'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(help_text='Business this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business User',
                'verbose_name_plural': 'Business Users',
                'db_table': 'business_user',
                'indexes': [models.Index(fields=['business'], name='idx_business_user_business'), models.Index(fields=['business', 'username', 'is_active'], name='idx_business_user_login'), models.Index(fields=['role'], name='idx_business_user_role')],
                'unique_together': {('business', 'username')},
            },
        ),
    ]
