# Generated by Django 6.0.2 on 2026-06-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='owned_businesses',
            field=models.ManyToManyField(blank=True, help_text='Businesses owned by this admin.', related_name='owners', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='business',
            field=models.ForeignKey(blank=True, help_text="Kasir belongs to 1 business. Admin doesn't belong to any specific business.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to='businesses.business'),
        ),
        migrations.AddConstraint(
            model_name='businessuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'admin')), fields=('username',), name='unique_admin_username'),
        ),
        migrations.AddConstraint(
            model_name='businessuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'kasir')), fields=('business', 'username'), name='unique_kasir_username'),
        ),
    ]
