# Generated by Django 6.0.2 on 2026-06-12 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_businessuser_unique_together_and_more'),
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessuser',
            name='unique_admin_username',
        ),
        migrations.RemoveConstraint(
            model_name='businessuser',
            name='unique_kasir_username',
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Primary business context for Kasir. Null for Admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='owned_businesses',
            field=models.ManyToManyField(blank=True, help_text='Businesses owned by this Admin.', related_name='owner_users', to='businesses.business'),
        ),
        migrations.AlterUniqueTogether(
            name='businessuser',
            unique_together={('business', 'username')},
        ),
    ]
