# Generated by Django 6.0.2 on 2026-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_businessuser_unique_admin_username_and_more'),
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='owner_code',
            field=models.CharField(blank=True, help_text='Unique 6-char code for admin login identity. Only for role=admin.', max_length=6, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='businessuser',
            index=models.Index(fields=['owner_code'], name='idx_business_user_owner_code'),
        ),
    ]
