# Generated by Django 6.0.2 on 2026-06-10 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_business_city_business_country_business_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(help_text='Snapshot nama user saat aksi dilakukan (tetap ada walau user dihapus)', max_length=100)),
                ('actor_role', models.CharField(help_text="Role user saat aksi: 'admin' atau 'kasir'", max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Membuat'), ('UPDATE', 'Mengubah'), ('DELETE', 'Menghapus'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VOID', 'Void Transaksi'), ('CHECKOUT', 'Checkout'), ('NOTIFY', 'Kirim Notifikasi'), ('PASSWORD', 'Ganti Password')], help_text='Tipe aksi yang dilakukan', max_length=20)),
                ('target_type', models.CharField(help_text='Tipe objek target: Product, Category, Transaction, dll', max_length=50)),
                ('target_id', models.IntegerField(blank=True, help_text='ID objek target (null jika tidak berlaku)', null=True)),
                ('description', models.TextField(help_text="Deskripsi human-readable: 'Mengubah harga Mie Goreng dari Rp 3.000 ke Rp 3.500'")),
                ('old_data', models.JSONField(blank=True, help_text='Data sebelum perubahan (JSON)', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Data setelah perubahan (JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address user saat aksi dilakukan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User yang melakukan aksi (null jika user sudah dihapus)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='accounts.businessuser')),
                ('business', models.ForeignKey(help_text='Bisnis yang memiliki log ini', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='audit_log_busines_34e482_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['actor'], name='audit_log_actor_i_8c3cd6_idx'), models.Index(fields=['target_type'], name='audit_log_target__219605_idx')],
            },
        ),
    ]
