# Generated by Django 6.0.2 on 2026-03-15 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_code', models.CharField(help_text='6 alphanumeric uppercase code (e.g., AB12CD). Rotatable for security.', max_length=6, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(blank=True, help_text='Warung, Toko Kelontong, Minimart, Cafe, etc.', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'business',
                'indexes': [models.Index(fields=['business_code'], name='idx_business_code'), models.Index(fields=['is_active'], name='idx_business_active')],
            },
        ),
        migrations.CreateModel(
            name='BusinessCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_code', models.CharField(blank=True, max_length=6, null=True)),
                ('new_code', models.CharField(max_length=6)),
                ('reason', models.CharField(blank=True, help_text='Reason for code rotation', max_length=200)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_history', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Code History',
                'verbose_name_plural': 'Business Code History',
                'db_table': 'business_code_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
