# Generated by Django 6.0.2 on 2026-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(default='Indonesia', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, help_text='Kecamatan', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
