# Generated by Django 6.0.2 on 2026-04-05 16:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0002_initial'),
        ('products', '0002_supplier_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(help_text='Unique transaction ID (receipt number)', max_length=30, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount (after discount)', max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount given', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card/Debit'), ('QRIS', 'QRIS'), ('TRANSFER', 'Bank Transfer'), ('EWALLET', 'E-Wallet'), ('MIXED', 'Mixed Payment')], default='CASH', help_text='Payment method used', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid by customer', max_digits=14)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Change returned to customer', max_digits=12)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='COMPLETED', help_text='Transaction status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional transaction notes')),
                ('cashier_name', models.CharField(blank=True, help_text='Cashier/operator name (for audit)', max_length=100)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of transaction')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business owner of this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit at time of sale', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Quantity x Price per unit', max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line item discount', max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, help_text='Batch/lot used for this item (FIFO)', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productbatch')),
                ('product', models.ForeignKey(help_text='Product sold', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='products.product')),
                ('transaction', models.ForeignKey(help_text='Parent transaction', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Item',
                'verbose_name_plural': 'Transaction Items',
                'db_table': 'transaction_item',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['business', 'transaction_date'], name='idx_trans_business_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['business', 'status'], name='idx_trans_business_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_code'], name='idx_trans_code'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['transaction'], name='idx_item_transaction'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['product'], name='idx_item_product'),
        ),
    ]
