# Generated by Django 6.0.2 on 2026-06-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-generated unique key to prevent double submissions', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding this transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was voided', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_by',
            field=models.CharField(blank=True, help_text='Who voided this transaction', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('VOIDED', 'Voided')], default='COMPLETED', help_text='Transaction status', max_length=20),
        ),
    ]
