# Generated by Django 6.0.2 on 2026-06-25 01:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_idempotency_key_transaction_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase cost per unit at time of sale (from batch.purchase_cost, for P&L calculation)', max_digits=12),
        ),
    ]
