# Generated by Django 6.0.2 on 2026-06-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionitem_cost_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card/Debit'), ('QRIS', 'QRIS'), ('TRANSFER', 'Bank Transfer'), ('EWALLET', 'E-Wallet'), ('MIXED', 'Mixed Payment'), ('XENDIT', 'Xendit Digital Payment')], default='CASH', help_text='Payment method used', max_length=20),
        ),
    ]
